theory Requirements
	imports ExtraInvariants
begin
definition inv where
"inv s =
((constants s)
\<and> (\<forall> sa6. (((toEnvP sa6) \<and> (substate sa6 s)) \<longrightarrow> (\<forall> sa1. ((((substate sa1 sa6) \<and> (toEnvP sa1)) \<and> ((\<exists> sa2. (((((substate sa2 sa1) \<and> (sa2 \<noteq> sa1)) \<and> (toEnvP sa2)) \<and> (\<forall> sa3. ((((substate sa2 sa3) \<and> (sa2 \<noteq> sa3)) \<and> ((substate sa3 sa1) \<and> (sa3 \<noteq> sa1))) \<longrightarrow> (\<not> (toEnvP sa3))))) \<and> ((\<not> (theBool (getVarVal sa2 ''lightPort_0'' []))) \<and> (\<not> (theBool (getVarVal sa2 ''buttonPort_0'' [])))))) \<and> (theBool (getVarVal sa1 ''buttonPort_0'' [])))) \<longrightarrow> ((\<forall> sa4. (((((substate sa1 sa4) \<and> (sa1 \<noteq> sa4)) \<and> (substate sa4 sa6)) \<and> (toEnvP sa4)) \<longrightarrow> (\<not> (theBool (getVarVal sa4 ''lightPort_0'' []))))) \<longrightarrow> (\<forall> sa5. ((((substate sa1 sa5) \<and> (substate sa5 sa6)) \<and> (toEnvP sa5)) \<longrightarrow> (\<not> (((toEnvNum sa1 sa5) * 100) \<ge> 15000)))))))))
\<and> (\<forall> sa11. (((toEnvP sa11) \<and> (substate sa11 s)) \<longrightarrow> ((\<exists> sa8. ((((substate sa8 sa11) \<and> (toEnvP sa8)) \<and> ((\<exists> sa9. (((((substate sa9 sa8) \<and> (sa9 \<noteq> sa8)) \<and> (toEnvP sa9)) \<and> (\<forall> sa10. ((((substate sa9 sa10) \<and> (sa9 \<noteq> sa10)) \<and> ((substate sa10 sa8) \<and> (sa10 \<noteq> sa8))) \<longrightarrow> (\<not> (toEnvP sa10))))) \<and> (\<not> (theBool (getVarVal sa9 ''lightPort_0'' []))))) \<and> (theBool (getVarVal sa8 ''lightPort_0'' [])))) \<and> (((toEnvNum sa8 sa11) * 100) < 30000))) \<longrightarrow> (theBool (getVarVal sa11 ''lightPort_0'' [])))))
\<and> (\<forall> sa18. (((toEnvP sa18) \<and> (substate sa18 s)) \<longrightarrow> (\<forall> sa13. ((((substate sa13 sa18) \<and> (toEnvP sa13)) \<and> ((\<exists> sa14. (((((substate sa14 sa13) \<and> (sa14 \<noteq> sa13)) \<and> (toEnvP sa14)) \<and> (\<forall> sa15. ((((substate sa14 sa15) \<and> (sa14 \<noteq> sa15)) \<and> ((substate sa15 sa13) \<and> (sa15 \<noteq> sa13))) \<longrightarrow> (\<not> (toEnvP sa15))))) \<and> (\<not> (theBool (getVarVal sa14 ''lightPort_0'' []))))) \<and> (theBool (getVarVal sa13 ''lightPort_0'' [])))) \<longrightarrow> ((\<forall> sa16. (((((substate sa13 sa16) \<and> (sa13 \<noteq> sa16)) \<and> (substate sa16 sa18)) \<and> (toEnvP sa16)) \<longrightarrow> (\<not> (\<not> (theBool (getVarVal sa16 ''lightPort_0'' [])))))) \<longrightarrow> (\<forall> sa17. ((((substate sa13 sa17) \<and> (substate sa17 sa18)) \<and> (toEnvP sa17)) \<longrightarrow> (\<not> (((toEnvNum sa13 sa17) * 100) \<ge> 30000)))))))))
\<and> (\<forall> sa25. (((toEnvP sa25) \<and> (substate sa25 s)) \<longrightarrow> (\<forall> sa20. ((((substate sa20 sa25) \<and> (toEnvP sa20)) \<and> ((\<exists> sa21. (((((substate sa21 sa20) \<and> (sa21 \<noteq> sa20)) \<and> (toEnvP sa21)) \<and> (\<forall> sa22. ((((substate sa21 sa22) \<and> (sa21 \<noteq> sa22)) \<and> ((substate sa22 sa20) \<and> (sa22 \<noteq> sa20))) \<longrightarrow> (\<not> (toEnvP sa22))))) \<and> (theBool (getVarVal sa21 ''lightPort_0'' [])))) \<and> (\<not> (theBool (getVarVal sa20 ''lightPort_0'' []))))) \<longrightarrow> ((\<forall> sa23. (((((substate sa20 sa23) \<and> (sa20 \<noteq> sa23)) \<and> (substate sa23 sa25)) \<and> (toEnvP sa23)) \<longrightarrow> (\<not> (theBool (getVarVal sa23 ''buttonPort_0'' []))))) \<longrightarrow> (\<forall> sa24. ((((substate sa20 sa24) \<and> (substate sa24 sa25)) \<and> (toEnvP sa24)) \<longrightarrow> (\<not> (theBool (getVarVal sa24 ''lightPort_0'' []))))))))))
\<and> (\<forall> sa30. (((toEnvP sa30) \<and> (substate sa30 s)) \<longrightarrow> ((\<exists> sa27. ((((substate sa27 sa30) \<and> (toEnvP sa27)) \<and> ((\<exists> sa28. (((((substate sa28 sa27) \<and> (sa28 \<noteq> sa27)) \<and> (toEnvP sa28)) \<and> (\<forall> sa29. ((((substate sa28 sa29) \<and> (sa28 \<noteq> sa29)) \<and> ((substate sa29 sa27) \<and> (sa29 \<noteq> sa27))) \<longrightarrow> (\<not> (toEnvP sa29))))) \<and> (theBool (getVarVal sa28 ''lightPort_0'' [])))) \<and> (\<not> (theBool (getVarVal sa27 ''lightPort_0'' []))))) \<and> (((toEnvNum sa27 sa30) * 100) < 15000))) \<longrightarrow> (\<not> (theBool (getVarVal sa30 ''lightPort_0'' []))))))
\<and> (\<forall> sa32. ((((toEnvP sa32) \<and> (substate sa32 s)) \<and> ((getPstate sa32 ''Controller'') = ''minimalRed'')) \<longrightarrow> ((\<not> (theBool (getVarVal sa32 ''lightPort_0'' []))) \<and> ((ltime sa32 ''Controller'') \<le> 10000))))
\<and> (\<forall> sa34. ((((toEnvP sa34) \<and> (substate sa34 s)) \<and> ((getPstate sa34 ''Controller'') = ''redAfterMinimalRed'')) \<longrightarrow> (\<not> (theBool (getVarVal sa34 ''lightPort_0'' [])))))
\<and> (\<forall> sa36. ((((toEnvP sa36) \<and> (substate sa36 s)) \<and> ((getPstate sa36 ''Controller'') = ''redToGreen'')) \<longrightarrow> ((\<not> (theBool (getVarVal sa36 ''lightPort_0'' []))) \<and> ((ltime sa36 ''Controller'') \<le> 5000))))
\<and> (\<forall> sa38. ((((toEnvP sa38) \<and> (substate sa38 s)) \<and> ((getPstate sa38 ''Controller'') = ''green'')) \<longrightarrow> (((theBool (getVarVal sa38 ''lightPort_0'' [])) \<and> (\<not> (theBool (getVarVal sa38 ''#bpressed'' [])))) \<and> ((ltime sa38 ''Controller'') \<le> 30000))))
\<and> (extra_states_Controller s))
"

end