theory Requirements
	imports PalletStationTheory
begin
definition inv where
"inv s =
((constants s)
\<and> (\<forall> sa1. (((toEnvP sa1) \<and> (substate sa1 s)) \<longrightarrow> (\<not> ((theBool (getVarVal sa1 ''drives_0'' [])) \<and> (theBool (getVarVal sa1 ''drives_1'' []))))))
\<and> (\<forall> sa4. ((((toEnvP sa4) \<and> (substate sa4 s)) \<and> (((getPstate sa4 ''Palletiser'') \<noteq> ''stop'') \<and> ((getPstate sa4 ''Palletiser'') \<noteq> ''error''))) \<longrightarrow> ((\<exists> sa3. ((((substate sa3 sa4) \<and> (toEnvP sa3)) \<and> (theBool (getVarVal sa3 ''sensors_1'' []))) \<and> (((toEnvNum sa3 sa4) * 100) < 2000))) \<longrightarrow> (\<not> ((theBool (getVarVal sa4 ''drives_0'' [])) \<or> (theBool (getVarVal sa4 ''drives_1'' [])))))))
\<and> (\<forall> sa9. ((((toEnvP sa9) \<and> (substate sa9 s)) \<and> (((getPstate sa9 ''Palletiser'') \<noteq> ''stop'') \<and> ((getPstate sa9 ''Palletiser'') \<noteq> ''error''))) \<longrightarrow> (\<forall> sa6. ((((substate sa6 sa9) \<and> (toEnvP sa6)) \<and> (theBool (getVarVal sa6 ''sensors_0'' []))) \<longrightarrow> ((\<forall> sa7. (((((substate sa6 sa7) \<and> (sa6 \<noteq> sa7)) \<and> (substate sa7 sa9)) \<and> (toEnvP sa7)) \<longrightarrow> (\<not> ((theBool (getVarVal sa7 ''drives_0'' [])) \<or> (theBool (getVarVal sa7 ''drives_1'' [])))))) \<longrightarrow> (\<forall> sa8. ((((substate sa6 sa8) \<and> (substate sa8 sa9)) \<and> (toEnvP sa8)) \<longrightarrow> (\<not> (((toEnvNum sa6 sa8) * 100) \<ge> 1000)))))))))
\<and> (\<forall> sa12. ((((toEnvP sa12) \<and> (substate sa12 s)) \<and> (((getPstate sa12 ''Palletiser'') \<noteq> ''stop'') \<and> ((getPstate sa12 ''Palletiser'') \<noteq> ''error''))) \<longrightarrow> (((getPstate sa12 ''Palletiser'') = ''packing'') \<longrightarrow> (\<exists> sa11. (((substate sa11 sa12) \<and> (toEnvP sa11)) \<and> ((getPstate sa11 ''Palletiser'') = ''scanning''))))))
\<and> (\<forall> sa14. ((((toEnvP sa14) \<and> (substate sa14 s)) \<and> (((getPstate sa14 ''Palletiser'') \<noteq> ''stop'') \<and> ((getPstate sa14 ''Palletiser'') \<noteq> ''error''))) \<longrightarrow> (((getPstate sa14 ''Palletiser'') = ''packing'') \<longrightarrow> ((ltime sa14 ''Palletiser'') < 30000))))
\<and> (\<forall> sa16. ((((toEnvP sa16) \<and> (substate sa16 s)) \<and> ((getPstate sa16 ''Palletiser'') = ''idle'')) \<longrightarrow> ((theBool (getVarVal sa16 ''drives_2'' [])) \<longrightarrow> (\<not> ((theBool (getVarVal sa16 ''drives_0'' [])) \<or> (theBool (getVarVal sa16 ''drives_1'' [])))))))
\<and> (\<forall> sa18. ((((toEnvP sa18) \<and> (substate sa18 s)) \<and> ((getPstate sa18 ''Palletiser'') = ''scanning'')) \<longrightarrow> ((theInt (getVarVal sa18 ''#scanned'' [])) \<ge> 0)))
\<and> (\<forall> sa20. ((((toEnvP sa20) \<and> (substate sa20 s)) \<and> ((getPstate sa20 ''Palletiser'') = ''sorting'')) \<longrightarrow> (((theInt (getVarVal sa20 ''#toLeft'' [])) + (theInt (getVarVal sa20 ''#toRight'' []))) \<le> ((theInt (getVarVal sa20 ''#BAY_COUNT'' [])) + (theInt (getVarVal sa20 ''#BAY_COUNT'' []))))))
\<and> (\<forall> sa22. ((((toEnvP sa22) \<and> (substate sa22 s)) \<and> ((getPstate sa22 ''Palletiser'') = ''packing'')) \<longrightarrow> ((theInt (getVarVal sa22 ''#placed'' [])) \<le> ((theInt (getVarVal sa22 ''#ROWS'' [])) * (theInt (getVarVal sa22 ''#COLS'' []))))))
\<and> (\<forall> sa25. ((((toEnvP sa25) \<and> (substate sa25 s)) \<and> (((getPstate sa25 ''Watchdog'') \<noteq> ''stop'') \<and> ((getPstate sa25 ''Watchdog'') \<noteq> ''error''))) \<longrightarrow> (\<forall> sa24. ((((substate sa24 sa25) \<and> (toEnvP sa24)) \<and> (theBool (getVarVal sa24 ''sensors_1'' []))) \<longrightarrow> (\<not> ((theBool (getVarVal sa25 ''drives_0'' [])) \<or> (theBool (getVarVal sa25 ''drives_1'' []))))))))
\<and> (\<forall> sa30. ((((toEnvP sa30) \<and> (substate sa30 s)) \<and> (((getPstate sa30 ''Watchdog'') \<noteq> ''stop'') \<and> ((getPstate sa30 ''Watchdog'') \<noteq> ''error''))) \<longrightarrow> (\<forall> sa27. ((((substate sa27 sa30) \<and> (toEnvP sa27)) \<and> (theBool (getVarVal sa27 ''sensors_0'' []))) \<longrightarrow> ((\<forall> sa28. (((((substate sa27 sa28) \<and> (sa27 \<noteq> sa28)) \<and> (substate sa28 sa30)) \<and> (toEnvP sa28)) \<longrightarrow> (\<not> (theBool (getVarVal sa28 ''sensors_1'' []))))) \<longrightarrow> (\<forall> sa29. ((((substate sa27 sa29) \<and> (substate sa29 sa30)) \<and> (toEnvP sa29)) \<longrightarrow> ((((toEnvNum sa27 sa29) * 100) \<ge> 1000) \<longrightarrow> ((getPstate sa29 ''Palletiser'') = ''packing'')))))))))
\<and> (\<forall> sa34. ((((toEnvP sa34) \<and> (substate sa34 s)) \<and> (((getPstate sa34 ''Watchdog'') \<noteq> ''stop'') \<and> ((getPstate sa34 ''Watchdog'') \<noteq> ''error''))) \<longrightarrow> (\<forall> sa32. ((((substate sa32 sa34) \<and> (toEnvP sa32)) \<and> (theBool (getVarVal sa32 ''sensors_0'' []))) \<longrightarrow> ((\<exists> sa33. ((((substate sa32 sa33) \<and> (substate sa33 sa34)) \<and> (toEnvP sa33)) \<and> ((theBool (getVarVal sa33 ''drives_0'' [])) \<or> (theBool (getVarVal sa33 ''drives_1'' []))))) \<or> (((toEnvNum sa32 sa34) * 100) < 500))))))
\<and> (\<forall> sa37. ((((toEnvP sa37) \<and> (substate sa37 s)) \<and> (((getPstate sa37 ''Watchdog'') \<noteq> ''stop'') \<and> ((getPstate sa37 ''Watchdog'') \<noteq> ''error''))) \<longrightarrow> (\<forall> sa36. ((((substate sa36 sa37) \<and> (toEnvP sa36)) \<and> (theBool (getVarVal sa36 ''sensors_1'' []))) \<longrightarrow> ((((toEnvNum sa36 sa37) * 100) < 300) \<longrightarrow> (\<not> ((theBool (getVarVal sa37 ''drives_0'' [])) \<or> (theBool (getVarVal sa37 ''drives_1'' [])))))))))
\<and> (\<forall> sa40. ((((toEnvP sa40) \<and> (substate sa40 s)) \<and> (((getPstate sa40 ''Watchdog'') \<noteq> ''stop'') \<and> ((getPstate sa40 ''Watchdog'') \<noteq> ''error''))) \<longrightarrow> ((\<exists> sa39. ((((substate sa39 sa40) \<and> (toEnvP sa39)) \<and> (theBool (getVarVal sa39 ''sensors_1'' []))) \<and> (((toEnvNum sa39 sa40) * 100) < 2000))) \<longrightarrow> (\<not> ((theBool (getVarVal sa40 ''drives_0'' [])) \<or> (theBool (getVarVal sa40 ''drives_1'' []))))))))
"

end