theory Requirements
	imports ExtraInvariants
begin
definition inv where
"inv s =
((constants s)
\<and> (\<forall> sa3. (((toEnvP sa3) \<and> (substate sa3 s)) \<longrightarrow> (((\<exists> sa1. (((((substate sa1 sa3) \<and> (sa1 \<noteq> sa3)) \<and> (toEnvP sa1)) \<and> (\<forall> sa2. ((((substate sa1 sa2) \<and> (sa1 \<noteq> sa2)) \<and> ((substate sa2 sa3) \<and> (sa2 \<noteq> sa3))) \<longrightarrow> (\<not> (toEnvP sa2))))) \<and> ((\<not> (theBool (getVarVal sa1 ''inp_1'' []))) \<and> (\<not> (theBool (getVarVal sa1 ''out_1'' [])))))) \<and> (theBool (getVarVal sa3 ''inp_1'' []))) \<longrightarrow> (theBool (getVarVal sa3 ''out_1'' [])))))
\<and> (\<forall> sa7. (((toEnvP sa7) \<and> (substate sa7 s)) \<longrightarrow> (((\<exists> sa5. (((((substate sa5 sa7) \<and> (sa5 \<noteq> sa7)) \<and> (toEnvP sa5)) \<and> (\<forall> sa6. ((((substate sa5 sa6) \<and> (sa5 \<noteq> sa6)) \<and> ((substate sa6 sa7) \<and> (sa6 \<noteq> sa7))) \<longrightarrow> (\<not> (toEnvP sa6))))) \<and> (\<not> (theBool (getVarVal sa5 ''out_1'' []))))) \<and> (\<not> (theBool (getVarVal sa7 ''inp_1'' [])))) \<longrightarrow> (\<not> (theBool (getVarVal sa7 ''out_1'' []))))))
\<and> (\<forall> sa14. (((toEnvP sa14) \<and> (substate sa14 s)) \<longrightarrow> (\<forall> sa9. ((((substate sa9 sa14) \<and> (toEnvP sa9)) \<and> ((\<exists> sa10. (((((substate sa10 sa9) \<and> (sa10 \<noteq> sa9)) \<and> (toEnvP sa10)) \<and> (\<forall> sa11. ((((substate sa10 sa11) \<and> (sa10 \<noteq> sa11)) \<and> ((substate sa11 sa9) \<and> (sa11 \<noteq> sa9))) \<longrightarrow> (\<not> (toEnvP sa11))))) \<and> ((theBool (getVarVal sa10 ''inp_1'' [])) \<and> (theBool (getVarVal sa10 ''out_1'' []))))) \<and> (\<not> (theBool (getVarVal sa9 ''inp_1'' []))))) \<longrightarrow> ((\<forall> sa12. (((((substate sa9 sa12) \<and> (sa9 \<noteq> sa12)) \<and> (substate sa12 sa14)) \<and> (toEnvP sa12)) \<longrightarrow> (\<not> ((\<not> (theBool (getVarVal sa12 ''out_1'' []))) \<or> (theBool (getVarVal sa12 ''inp_1'' [])))))) \<longrightarrow> (\<forall> sa13. ((((substate sa9 sa13) \<and> (substate sa13 sa14)) \<and> (toEnvP sa13)) \<longrightarrow> (\<not> (((toEnvNum sa9 sa13) * 100) \<ge> 2000)))))))))
\<and> (\<forall> sa18. (((toEnvP sa18) \<and> (substate sa18 s)) \<longrightarrow> (((\<exists> sa16. (((((substate sa16 sa18) \<and> (sa16 \<noteq> sa18)) \<and> (toEnvP sa16)) \<and> (\<forall> sa17. ((((substate sa16 sa17) \<and> (sa16 \<noteq> sa17)) \<and> ((substate sa17 sa18) \<and> (sa17 \<noteq> sa18))) \<longrightarrow> (\<not> (toEnvP sa17))))) \<and> (theBool (getVarVal sa16 ''out_1'' [])))) \<and> (theBool (getVarVal sa18 ''inp_1'' []))) \<longrightarrow> (theBool (getVarVal sa18 ''out_1'' [])))))
\<and> (\<forall> sa25. (((toEnvP sa25) \<and> (substate sa25 s)) \<longrightarrow> (\<forall> sa20. ((((substate sa20 sa25) \<and> (toEnvP sa20)) \<and> ((\<exists> sa21. (((((substate sa21 sa20) \<and> (sa21 \<noteq> sa20)) \<and> (toEnvP sa21)) \<and> (\<forall> sa22. ((((substate sa21 sa22) \<and> (sa21 \<noteq> sa22)) \<and> ((substate sa22 sa20) \<and> (sa22 \<noteq> sa20))) \<longrightarrow> (\<not> (toEnvP sa22))))) \<and> ((theBool (getVarVal sa21 ''inp_1'' [])) \<and> (theBool (getVarVal sa21 ''out_1'' []))))) \<and> (\<not> (theBool (getVarVal sa20 ''inp_1'' []))))) \<longrightarrow> ((\<forall> sa23. (((((substate sa20 sa23) \<and> (sa20 \<noteq> sa23)) \<and> (substate sa23 sa25)) \<and> (toEnvP sa23)) \<longrightarrow> (\<not> ((\<not> (theBool (getVarVal sa23 ''out_1'' []))) \<or> (theBool (getVarVal sa23 ''inp_1'' [])))))) \<longrightarrow> (\<forall> sa24. ((((substate sa20 sa24) \<and> (substate sa24 sa25)) \<and> (toEnvP sa24)) \<longrightarrow> (((getPstate sa24 ''Dryer'') = ''Work'') \<and> (\<not> (((toEnvNum sa20 sa24) * 100) \<ge> ((ltime sa24 ''Dryer'') - 100)))))))))))
\<and> (\<forall> sa27. ((((toEnvP sa27) \<and> (substate sa27 s)) \<and> ((getPstate sa27 ''Dryer'') = ''Wait'')) \<longrightarrow> (\<not> (theBool (getVarVal sa27 ''out_1'' [])))))
\<and> (\<forall> sa29. ((((toEnvP sa29) \<and> (substate sa29 s)) \<and> ((getPstate sa29 ''Dryer'') = ''Work'')) \<longrightarrow> (theBool (getVarVal sa29 ''out_1'' []))))
\<and> (\<forall> sa31. ((((toEnvP sa31) \<and> (substate sa31 s)) \<and> ((getPstate sa31 ''Dryer'') = ''Work'')) \<longrightarrow> ((theBool (getVarVal sa31 ''inp_1'' [])) \<longrightarrow> ((ltime sa31 ''Dryer'') = 100))))
\<and> (extra_states_Dryer s))
"

end